# Medium system for implementing sharded MongoDB storage
# - Config DB is a replica set with only 1 replica
# - 3 shards
#   -> Each shard is a replica set with 2 replicas and 1 arbiter

version: '3'

services:
  # Web server
  reco-storage-web:
    image: reco-storage-webapp
    ports:
      - "8080:8080"
    depends_on:
      - reco-storage-router
    deploy:
      replicas: 1
  
  # MongoDB mongos router
  reco-storage-router:
    image: reco-storage-mongodb
    entrypoint:
      - mongos
      - --configdb
      - configset/config-r0:27017
    depends_on:
      - config-r0
    deploy:
      replicas: 1

  # Config replica set
  config-r0:
    image: reco-storage-mongodb
    volumes:
      - cfr0:/data/db
    entrypoint:
      - mongod
      - --configsvr
      - --replSet
      - "configset"
      - --dbpath
      - /data/db
      - --smallfiles
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.config == true
          - node.labels.replicanum == 0
  
  # Shard 0 replica set
  shard0-r0:
    image: reco-storage-mongodb
    volumes:
      - s0r0:/data/db
    entrypoint:
      - mongod
      - --shardsvr
      - --replSet
      - "shard0set"
      - --dbpath
      - /data/db
      - --smallfiles
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.shard0 == true
          - node.labels.replicanum == 0

  shard0-r1:
    image: reco-storage-mongodb
    volumes:
      - s0r1:/data/db
    entrypoint:
      - mongod
      - --shardsvr
      - --replSet
      - "shard0set"
      - --dbpath
      - /data/db
      - --smallfiles
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.shard0 == true
          - node.labels.replicanum == 1

  shard0-arb:
    image: reco-storage-mongodb
    volumes:
      - s0ar:/data/db
    entrypoint:
      - mongod
      - --replSet
      - "shard0set"
      - --dbpath
      - /data/db
      - --smallfiles
      - --nojournal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # Shard 1 replica set
  shard1-r0:
    image: reco-storage-mongodb
    volumes:
      - s1r0:/data/db
    entrypoint:
      - mongod
      - --shardsvr
      - --replSet
      - "shard1set"
      - --dbpath
      - /data/db
      - --smallfiles
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.shard1 == true
          - node.labels.replicanum == 0

  shard1-r1:
    image: reco-storage-mongodb
    volumes:
      - s1r1:/data/db
    entrypoint:
      - mongod
      - --shardsvr
      - --replSet
      - "shard1set"
      - --dbpath
      - /data/db
      - --smallfiles
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.shard1 == true
          - node.labels.replicanum == 1

  shard1-arb:
    image: reco-storage-mongodb
    volumes:
      - s1ar:/data/db
    entrypoint:
      - mongod
      - --replSet
      - "shard1set"
      - --dbpath
      - /data/db
      - --smallfiles
      - --nojournal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # Shard 2 replica set
  shard2-r0:
    image: reco-storage-mongodb
    volumes:
      - s2r0:/data/db
    entrypoint:
      - mongod
      - --shardsvr
      - --replSet
      - "shard2set"
      - --dbpath
      - /data/db
      - --smallfiles
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.shard2 == true
          - node.labels.replicanum == 0

  shard2-r1:
    image: reco-storage-mongodb
    volumes:
      - s2r1:/data/db
    entrypoint:
      - mongod
      - --shardsvr
      - --replSet
      - "shard2set"
      - --dbpath
      - /data/db
      - --smallfiles
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.shard2 == true
          - node.labels.replicanum == 1

  shard2-arb:
    image: reco-storage-mongodb
    volumes:
      - s2ar:/data/db
    entrypoint:
      - mongod
      - --replSet
      - "shard2set"
      - --dbpath
      - /data/db
      - --smallfiles
      - --nojournal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  cfr0:
  s0r0:
  s0r1:
  s0ar:
  s1r0:
  s1r1:
  s1ar:
  s2r0:
  s2r1:
  s2ar:
