# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.artist import Artist
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ArtistList(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, artists: List[Artist]=None):
        """
        ArtistList - a model defined in Swagger

        :param artists: The artists of this ArtistList.
        :type artists: List[Artist]
        """
        self.swagger_types = {
            'artists': List[Artist]
        }

        self.attribute_map = {
            'artists': 'artists'
        }

        self._artists = artists

    @classmethod
    def from_dict(cls, dikt) -> 'ArtistList':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The artistList of this ArtistList.
        :rtype: ArtistList
        """
        return deserialize_model(dikt, cls)

    @property
    def artists(self) -> List[Artist]:
        """
        Gets the artists of this ArtistList.

        :return: The artists of this ArtistList.
        :rtype: List[Artist]
        """
        return self._artists

    @artists.setter
    def artists(self, artists: List[Artist]):
        """
        Sets the artists of this ArtistList.

        :param artists: The artists of this ArtistList.
        :type artists: List[Artist]
        """
        if artists is None:
            raise ValueError("Invalid value for `artists`, must not be `None`")

        self._artists = artists

