# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DefaultErrorResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message: str=None):
        """
        DefaultErrorResponse - a model defined in Swagger

        :param message: The message of this DefaultErrorResponse.
        :type message: str
        """
        self.swagger_types = {
            'message': str
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'DefaultErrorResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The defaultErrorResponse of this DefaultErrorResponse.
        :rtype: DefaultErrorResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """
        Gets the message of this DefaultErrorResponse.

        :return: The message of this DefaultErrorResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this DefaultErrorResponse.

        :param message: The message of this DefaultErrorResponse.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")

        self._message = message

